# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    working_directory: ~/$CIRCLE_WORKING_DIRECTORY/testing
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
orbs:
  node: circleci/node@4.1.0
workflows:
  test_my_app:
    jobs:
      - test

