# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@1.1.0
jobs:
  build:
    working_directory: ~/project
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout:
          path: ~/project
      - node/with-cache:
          steps:
            - run: npm run install-all
      - run:
          command: npm start
          background: true
      - run: sleep 5
workflows:
  testing:
    jobs:
      - build
