# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    test:
        steps:
        - checkout
        - run: mocha ./tests/server.test.js
        
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "run"
  run:
    # run tests
    jobs:
      - test
