# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    docker:
    - image: cimg/ruby:2.7.1-node
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    test:
        steps:
        - checkout
        - run: mocha ./tests/server.test.js
        
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "run"
  run:
    # run tests
    jobs:
      - test
